site_name: MameBotヘルプ
site_url: https://mamebot.readthedocs.io/
copyright: ©2021 MameBot運営

theme:
  name: 'material'
  language: ja
  features:
    - navigation.tabs
    - navigation.top
  logo: https://media.mamebot.gq/icon-r-500px.png
  favicon: https://media.mamebot.gq/icon-r-100px.png
  palette:
    primary: green
    accent: light green

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - ホーム: index.md
  - コマンド: commands/index.md
  - 機能: features/index.md

extra:
  social:
    - icon: fontawesome/solid/globe-asia
      link: https://mamebot.gq/
      name: ホームページ
    - icon: fontawesome/brands/discord
      link: https://mamebot.gq/support
      name: サポートサーバー
